### ISSUE TITLE
Error when running demo.py: missing network

### ISSUE THREAD

**Issue by O3Oalreadytaken** [morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5#2]
Hello~:D
I follow the steps of the readme
(after python setup.py build_ext --inplace
python setup.py build_ext install
python setup.py build_ext --inplace
Download pre-trained VGG16 to  "data\imagenet_weights\vgg16.ckpt
Run python train.py)

and then I run demo.py,but something went wrong :(

(tensorflow) D:\Faster-RCNN-TensorFlow-Python3.5-master>python demo.py
Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    'our server and place them properly?').format(tfmodel + '.meta'))
OSError: default\voc_2007_train\default\vgg16_faster_rcnn_iter_9000.ckpt.meta not found.
Did you download the proper networks from our server and place them properly?

**Comment by O3Oalreadytaken** [comment]
oops, I found that my train was not finish, so there is no file that demo.py need.

How many pictures that train.py will download?
It always stops in halfway (After downloading 90or300or1400 pictures, It stopped.)Q_Q

update
I delete most of the xml in the Annotation_imagenet,and the cmd can finish train.
but\..\Faster-RCNN-TensorFlow-Python3.5-master\default\voc_2007_train\default don't have vgg16_faster_rcnn_iter_9000.ckpt.meta QAQ

**Comment by morpheusthewhite** [comment]
If you delete .xml files in Annotation_imagenet then no train will be done so no checkpoint will be saved. 

train.py will download as many pictures as possible for the given classes (from imagenet)

**Comment by morpheusthewhite** [comment]
I fixed the naming of the model, now it should correctly work

**Comment by MsRabbits** [comment]
HI, dbeker, I found that there is no test file in your project, and i want to check the precise and recall of the model i have trained. Does the test file exist there? looing forward to your reply, thx!!!

**Comment by morpheusthewhite** [comment]
This is no dBeker project.

https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/86
