### ISSUE TITLE
building 'pycocotools._mask' extension error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by sdzbft** [morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5#3]
![image](https://user-images.githubusercontent.com/18287085/61954186-d9a22100-afea-11e9-937e-e124bd242f9c.png)

i don't know what file does the system want to find
and i haven't found a solution so far, could you help me,
thanks in advance.

win7
python 3.5.0

**Comment by morpheusthewhite** [comment]
Did you install all dependencies (including `cython`)?

**Comment by sdzbft** [comment]
Thank you for your prompt reply
I have installed all the dependencies in requirement.txt  
![image](https://user-images.githubusercontent.com/18287085/61957858-c5622200-aff2-11e9-8c3f-26b0d8b46e1a.png)

i don't know how to solve it, and I've tried to find any possible answer in issues but found nothing useful, Have you ever encountered this problem?

**Comment by morpheusthewhite** [comment]
Repeat the process from the beginning (also download again the folder) to make sure no file is missing

**Comment by sdzbft** [comment]
I've tried. but get the same mistake,,
i doubt if it is the the result of VS2017's environment??

I tried it on my friend's computer, when i run `python setup.py build_ext --inplace`, encounters error: Unable to find vcvarsall.bat

**Comment by morpheusthewhite** [comment]
Here you can find the same issue (about `vcvarsall.bat`)

https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/76

**Comment by sdzbft** [comment]
> Here you can find the same issue (about `vcvarsall.bat`)
> 
> [dBeker#76](https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/76)

Verrrrrry thanks for your kind help!! 
I have solved this problem by installing python tools(in VS2017) and rebooting the computer(i don't know why), this [blog](https://blog.csdn.net/qq_41895190/article/details/82877883) also help me a lot.

thanks again!!
