### ISSUE TITLE
How to train my model with COCO?

### ISSUE THREAD

**Issue by JXMss** [morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5#5]
Thx u for ur code. I want to train my model with COCO dataset.
I noticed that there is a coco.py in /lib/datasets, but I dont know how to use it.
Any assistance rendered me would be highly appreciated.

**Comment by morpheusthewhite** [comment]
I cannot give you a very specific help, but I know you must implement some missing part of code, like in `Faster-RCNN-TensorFlow-Python3/lib/datasets/factory.py` (you can follow the existing code referring to VOC dataset)

**Comment by JXMss** [comment]
thx a lot

**Comment by JXMss** [comment]
There is no "coco2017", only coco2014/2015

**Comment by morpheusthewhite** [comment]
And then? Can't you use them?
